"""Build the offline phone web app into docs/ (served by GitHub Pages).

Run:  python build_web.py
Writes docs/cards.json, docs/manifest.webmanifest, docs/sw.js and the app icons.
docs/index.html is hand-written and left alone.
"""
import hashlib
import json
import struct
import zlib
from pathlib import Path

from curriculum import CURRICULUM
from flashcards import BANK

DOCS = Path(__file__).parent / "docs"


# ---------------------------------------------------------------- cards.json
def build_cards():
    pools, index, mapping = [], {}, {}
    for (course, unit), cards in sorted(BANK.items()):
        key = tuple(cards)
        if key not in index:  # ELA units are shared by many courses; store them once
            index[key] = len(pools)
            pools.append([[f, b] for f, b in cards])
        mapping[f"{course}|{unit}"] = index[key]
    data = {"curr": CURRICULUM, "pools": pools, "map": mapping}
    text = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    (DOCS / "cards.json").write_text(text, encoding="utf-8")
    return len(pools), sum(len(p) for p in pools), len(text.encode("utf-8"))


# ---------------------------------------------------------------- icons (pure Python PNG)
def rounded_rect_cover(x, y, x0, y0, x1, y1, r):
    if x < x0 or x > x1 or y < y0 or y > y1:
        return False
    cx = min(max(x, x0 + r), x1 - r)
    cy = min(max(y, y0 + r), y1 - r)
    return (x - cx) ** 2 + (y - cy) ** 2 <= r * r


def make_icon(size):
    blue, light, white = (11, 95, 255), (170, 200, 255), (255, 255, 255)
    s = size / 512.0
    back = (110 * s, 120 * s, 380 * s, 330 * s, 36 * s)
    front = (135 * s, 170 * s, 405 * s, 395 * s, 36 * s)
    bars = [(175 * s, 225 * s, 365 * s, 245 * s), (175 * s, 270 * s, 335 * s, 290 * s),
            (175 * s, 315 * s, 300 * s, 335 * s)]
    rows = []
    for py in range(size):
        row = bytearray([0])
        for px in range(size):
            acc = [0, 0, 0]
            for sy in (0.25, 0.75):
                for sx in (0.25, 0.75):
                    x, y = px + sx, py + sy
                    c = blue
                    if rounded_rect_cover(x, y, *back):
                        c = light
                    if rounded_rect_cover(x, y, *front):
                        c = white
                        if any(b[0] <= x <= b[2] and b[1] <= y <= b[3] for b in bars):
                            c = blue
                    acc = [a + v for a, v in zip(acc, c)]
            row += bytes(a // 4 for a in acc)
        rows.append(bytes(row))
    raw = b"".join(rows)

    def chunk(tag, body):
        c = struct.pack(">I", len(body)) + tag + body
        return c + struct.pack(">I", zlib.crc32(tag + body) & 0xFFFFFFFF)

    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    return png


# ---------------------------------------------------------------- manifest + service worker
MANIFEST = {
    "name": "Alberta Flash Cards",
    "short_name": "AB Cards",
    "description": "Study Alberta Grade 9-12 flash cards offline.",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "orientation": "portrait",
    "background_color": "#ffffff",
    "theme_color": "#0b5fff",
    "icons": [
        {"src": "icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any maskable"},
        {"src": "icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable"},
    ],
}

SW = """// Generated by build_web.py - do not edit.
const CACHE = 'abfc-%(version)s';
const ASSETS = ['./', 'index.html', 'cards.json', 'manifest.webmanifest', 'icon-192.png', 'icon-512.png'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('abfc-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request, {ignoreSearch: true}).then(hit => hit || fetch(e.request).catch(() => caches.match('index.html')))
  );
});
"""


def main():
    DOCS.mkdir(exist_ok=True)
    pools, cards, size = build_cards()
    for n in (192, 512):
        (DOCS / f"icon-{n}.png").write_bytes(make_icon(n))
    (DOCS / "manifest.webmanifest").write_text(json.dumps(MANIFEST, indent=2), encoding="utf-8")
    digest = hashlib.sha1()
    for name in ("cards.json", "index.html"):
        path = DOCS / name
        if path.exists():
            digest.update(path.read_bytes())
    (DOCS / "sw.js").write_text(SW % {"version": digest.hexdigest()[:10]}, encoding="utf-8")
    print(f"Wrote docs/: {pools} card lists, {cards} cards, cards.json {size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
